# Site configuration. This file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change it, restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Léon Zheng"
title_separator          : "-"
name                     : &name "Léon Zheng"
description              : &description "Researcher at Huawei"
url                      : https://leonzheng2.github.io
baseurl                  : ""
repository               : "leonzheng2/leonzheng2.github.io"
breadcrumbs              : false
words_per_minute         : 160
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts


# Analytics
analytics:
  provider               :  "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             : "Léon Zheng"
  avatar           : "profile.jpg"
  bio              : "Researcher at Huawei <br> <i>leon.zheng [at] polytechnique [dot] org</i>"
  location         : "Paris, France"
  googlescholar    : "https://scholar.google.com/citations?user=7gq9f6CfBnAC&hl"
  github           : "leonzheng2"
  linkedin         : "leon-zheng"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - README.md
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  thesis:
    output: true
    permalink: /:collection/:path/
  preprint:
    output: true
    permalink: /:collection/:path/
  journal:
    output: true
    permalink: /:collection/:path/
  conference:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
